### ISSUE TITLE
Where is the training data used to train the Critical model

### ISSUE THREAD

**Issue by liuyukid** [debjitpaul/refiner#1]

**Comment by debjitpaul** [comment]
### I appreciate your interest in our work. 

To create the critic data. You need to follow the following steps: 

>  Download the original training data for each task. 
>  Example, for the Moral Stories task,  run  `data_preprocessing/prepare_moral_stories_for_critic.py` to create the critic data for the moral story task. 

Please feel free to contact me incase you need any help.
