### ISSUE TITLE
遇到报错，ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds

### ISSUE THREAD

**Issue by zzyd123** [debjitpaul/refiner#2]
请问执行python3 src/scripts/finetune.py --training-file refiner-main/data/mwp/critique_train.json --validation-file refiner-main/data/mwp/critique_val.json --language-model /raid/model/flan--T5--base --model-dir /raid/model/flan--T5--large --epochs 10 --batch-size 8   这条指令的时候，为什么遇到报错ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds呢？

**Comment by debjitpaul** [comment]
T5 is an encoder-decoder model, so you must provide both input_ids and decoder_input_ids to the model. Maybe taking a look at the [T5 docs](https://huggingface.co/transformers/model_doc/t5.html#transformers.T5Model.forward) (especially the "Examples") can help you :-)

**Comment by zzyd123** [comment]
> 
thankyou！
